# Generated by Django 5.2.7 on 2025-10-31 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuizCultural", "0002_alter_mtcars_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "texto",
                    models.CharField(help_text="Texto da pergunta", max_length=255),
                ),
                (
                    "opcao_a",
                    models.CharField(help_text="Alternativa A", max_length=100),
                ),
                (
                    "opcao_b",
                    models.CharField(help_text="Alternativa B", max_length=100),
                ),
                (
                    "opcao_c",
                    models.CharField(help_text="Alternativa C", max_length=100),
                ),
                (
                    "opcao_d",
                    models.CharField(help_text="Alternativa D", max_length=100),
                ),
                (
                    "resposta_correta",
                    models.CharField(
                        help_text="Letra da alternativa correta (A, B, C ou D)",
                        max_length=1,
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        blank=True,
                        help_text="Categoria da pergunta (opcional)",
                        max_length=100,
                    ),
                ),
                (
                    "dificuldade",
                    models.CharField(
                        blank=True,
                        help_text="Nível de dificuldade (opcional)",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MTCars",
        ),
    ]
