# Generated by Django 5.2.2 on 2025-06-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuizCultural", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mtcars",
            name="name",
            field=models.CharField(db_column="NAME"),
        ),
    ]
